name: Update REST API endpoint methods
on:
  repository_dispatch:
    types: [octokit-routes-release]

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run generate-routes
      - name: configure git user.email and user.name
        run: |
          git config --global user.email 'octokitbot@martynus.net'
          git config --global user.name 'Octokit Bot'
      - run: |
          'git commit -a -m "build: routes" --author="Octokit Bot <octokitbot@martynus.net>"'
          git push "https://x-access-token:${GH_TOKEN}@github.com/octokit/rest.js" patch-${GITHUB_SHA}
          npx octokit-cli pulls create --owner octokit --repo rest.js --base master --head patch-${GITHUB_SHA} --title "octokit/routes update"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: git ls-files -m
